-- AlterTable: add ENROLLED_ONLY to ClassStatus enum
ALTER TABLE `Class` MODIFY COLUMN `status` ENUM('ANYONE', 'STUDENTS_ONLY', 'ENROLLED_ONLY', 'PAID_ONLY', 'PRIVATE', 'INACTIVE') NOT NULL DEFAULT 'ANYONE';
