-- AlterTable: add ENROLLED_ONLY to LectureStatus enum
ALTER TABLE `Lecture` MODIFY COLUMN `status` ENUM('ANYONE', 'STUDENTS_ONLY', 'ENROLLED_ONLY', 'PAID_ONLY', 'PRIVATE', 'INACTIVE') NOT NULL DEFAULT 'STUDENTS_ONLY';
